package com.microfinance.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * One row of the printed "Loan Card / Repayment Schedule" sheet — the
 * expected EMI demand for a given installment, plus whatever has actually
 * been collected against it so far. Generated by LoanScheduleCalculator from
 * the member's loanAmount / totalWeeks / interestPercentage / weeklyAmount,
 * NOT stored as its own table — recomputed on every read so it always
 * reflects the member's current loan terms.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LoanInstallmentResponse {

    /** 1-based installment number (matches the "S.No" column). */
    private int installmentNo;

    /** Date this installment is due. */
    private LocalDate demandDate;

    private BigDecimal demandPrincipal;
    private BigDecimal demandInterest;
    private BigDecimal demandTotal;

    /**
     * Filled in only once an actual payment has been matched to this
     * installment (see LoanScheduleCalculator's payment-matching pass).
     * Null/left blank on the printed sheet until then.
     */
    private BigDecimal collectedPrincipal;
    private BigDecimal collectedInterest;
    private BigDecimal collectedTotal;
    private LocalDate collectionDate;
    private String receiptNo;
}